dependencies:
- name: mysql
  version: "^0.8.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: redis
  version: "^3.4.1"
  repository: "https://kubernetes-charts.storage.googleapis.com"