# nginx configmap
apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  proxy-body-size: "200m"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  namespace: {{ .Value.namespace }}
  name: nginx

---
# nginx ingress ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress
  namespace: {{ .Value.namespace }}

---
# nginx service
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Value.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx

---
# nginx deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Value.namespace }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: ingress
      containers:
      - image: {{ .Value.nginx.image }}
        name: nginx
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-tcp-services