{{- if .Values.rbac.enabled -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: pod-writer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
# Full read access to the api and resources
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: pod-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
{{- end -}}