apiVersion: v1
kind: Secret
metadata:
  name: sd-buildbot-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: sd-buildbot
type: kubernetes.io/service-account-token