---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "store.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: store
    env: {{ .Values.env }}
    tier: svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: store
    env: {{ .Values.env }}
    tier: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "store.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: store
    env: {{ .Values.env }}
    tier: app
spec:
  replicas: {{ .Values.store.replicas }}
  selector:
    matchLabels:
      app: store
      env: {{ .Values.env }}
      tier: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: store
        env: {{ .Values.env }}
        tier: app
    spec:
      containers:
      - env:
        - name: SECRET_JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: jwtpublickey
              name: screwdriver-api-secrets
        {{- if .Values.store.s3.useAccessKey }}
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: keyid
              name: screwdriver-store-secrets
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: screwdriver-store-secrets
        {{- end }}
        - name: S3_REGION
          value: {{ .Values.store.s3.region }}
        - name: S3_BUCKET
          value: {{ .Values.store.s3.bucketName }}
        - name: STRATEGY
          {{- if .Values.store.s3.enabled }}
          value: s3
          {{- else }}
          value: memory
          {{- end }}
        - name: BUILDS_EXPIRE_TIME
          value: "7776000000"
        - name: URI
          value: {{ template "store.uri" . }}
        - name: ECOSYSTEM_UI
          value: {{ template "ui.uri" . }}
        - name: S3_SIG_VER
          value: "v4"
        # Currently uses a private docker image because the updated version wasn't published yet
        image: {{ .Values.store.image }}
        imagePullPolicy: IfNotPresent
        name: screwdriver-store
        ports:
        - containerPort: 80
          protocol: TCP
