apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: ui
    tier: svc
    env: {{ .Values.env }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ui
    tier: app
    env: {{ .Values.env }}
---
# requires service account to be created
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: ui
    env: {{ .Values.env }}
    tier: app
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: ui
      env: {{ .Values.env }}
      tier: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
        tier: app
        env: {{ .Values.env }}
    spec:
      containers:
      - name: screwdriver-ui
        image: {{ .Values.ui.image }}
        ports:
        - containerPort: 80
        env:
          {{- if .Values.ingress.singleHost.enabled }}
          - name: ROOT_URL
            value: {{ .Values.ingress.singleHost.uiPath }}
          {{- end }}
          - name: AVATAR_HOSTNAME
            value: "{{ .Values.ui.avatarHost }}"
          - name: ECOSYSTEM_API
            value: {{ template "api.uri" . }}
          - name: ECOSYSTEM_STORE
            value: {{ template "store.uri" . }}
