---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sdstore
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.store.replicas }}
  selector:
    matchLabels:
      app: screwdriver
      tier: store
      env: {{ .Values.common.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: screwdriver
        tier: store
        env: {{ .Values.common.env }}
    spec:
      containers:
      - name: screwdriver-store
        image: {{ .Values.store.image }}
        ports:
        - containerPort: 80
        # Validate that the service is started
        livenessProbe:
          httpGet:
            path: /v1/status
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        # Validate that the service is reached
        readinessProbe:
          httpGet:
            path: /v1/status
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        # Environment variables that point to your secrets in your secrets.yaml
        env:
          - name: SECRET_JWT_PUBLIC_KEY
            value: |
              {{- include "jwt_public" . | indent 14}}
          # 90 day expiration of logs
          - name: BUILDS_EXPIRE_TIME
            value: "7776000000"
          - name: URI
            value: {{ include "ecosystem_store" . }}
          - name: ECOSYSTEM_UI
            value: {{ include "ecosystem_ui" . }}
