---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sdui
  namespace: {{ .Values.common.namespace }}
  labels:
    app: screwdriver
    tier: ui
    env: {{ .Values.common.env }}
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.ui.nodePort }}
    targetPort: 80
  selector:
    app: screwdriver
    tier: ui
    env: {{ .Values.common.env }}